version: '3.5'

services:

### hysteria-arm ############################################
    hysteria-arm:
      image: tobyxdd/hysteria:latest
      build: ./hysteria-arm
      command: ["server", "--config", "/etc/config.json"]
      network_mode: "host"
      environment:
        - TZ=${WORKSPACE_TIMEZONE}
      volumes:
        - ${NGINX_SSL_PATH}:/etc/ssl
        - ./hysteria/hysteria-arm.json:/etc/config.json

### hysteria-amd ############################################
    hysteria-amd:
      image: tobyxdd/hysteria:latest
      build: ./hysteria-amd
      command: ["server", "--config", "/etc/config.json"]
      network_mode: "host"
      environment:
        - TZ=${WORKSPACE_TIMEZONE}
      volumes:
        - ${NGINX_SSL_PATH}:/etc/ssl
        - ./hysteria/hysteria-amd.json:/etc/config.json

### tuic-client ##############################################
    tuic-client:
      build: ./tuic-client
      restart: always
      network_mode: "host"
      environment:
        - TZ=${WORKSPACE_TIMEZONE}
      volumes:
        - ./tuic-client/config.json:/etc/tuic/config.json
