name: laradock
services:
  mariadb:
    build:
      context: /Users/kilvn/Documents/web/laradock/mariadb
      dockerfile: ./mariadb/Dockerfile
      args:
        MARIADB_VERSION: latest
        http_proxy: null
        https_proxy: null
        no_proxy: null
    environment:
      MYSQL_DATABASE: default
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      TZ: PRC
    image: mariadb:latest
    networks:
      backend: null
    ports:
    - mode: ingress
      target: 3306
      published: "3306"
      protocol: tcp
    restart: always
    volumes:
    - type: bind
      source: /Users/kilvn/.laradock/data/mariadb
      target: /var/lib/mysql
      bind:
        create_host_path: true
    - type: bind
      source: /Users/kilvn/Documents/web/laradock/mariadb/docker-entrypoint-initdb.d
      target: /docker-entrypoint-initdb.d
      bind:
        create_host_path: true
  nginx:
    build:
      context: /Users/kilvn/Documents/web/laradock/nginx
      dockerfile: ./nginx/Dockerfile
      args:
        CHANGE_SOURCE: "false"
        PHP_UPSTREAM_CONTAINER: php-fpm
        PHP_UPSTREAM_PORT: "9000"
        http_proxy: null
        https_proxy: null
        no_proxy: null
    depends_on:
      php-fpm:
        condition: service_started
    environment:
      TZ: PRC
    image: nginx:alpine
    networks:
      backend:
        aliases:
        - dev-bm.inboyu.com
        - dev-cc.inboyu.com
        - dev-uc.inboyu.com
        - dev-voc.inboyu.com
        - dev-op.inboyu.com
        - dev-dc.inboyu.com
        - dev.inboyu.com
        - dev-ec.inboyu.com
        - dev-vf.inboyu.com
        - dev-fm.inboyu.com
        - dev-dgc.inboyu.com
        - dev-amb.inboyu.com
        - boyu-platform-test.inboyu.com
        - dev-platform.inboyu.com
        - dev-exc.inboyu.com
        - dev-vm.inboyu.com
        - dev-am.inboyu.com
        - dev-md.inboyu.com
        - dev-qy.inboyu.com
        - dev-ac.inboyu.com
        - dev-scc.inboyu.com
        - dev-api.inboyu.com
        - data-encryption-service
      frontend:
        aliases:
        - dev-bm.inboyu.com
        - dev-cc.inboyu.com
        - dev-uc.inboyu.com
        - dev-voc.inboyu.com
        - dev-op.inboyu.com
        - dev-dc.inboyu.com
        - dev.inboyu.com
        - dev-ec.inboyu.com
        - dev-vf.inboyu.com
        - dev-fm.inboyu.com
        - dev-dgc.inboyu.com
        - dev-amb.inboyu.com
        - boyu-platform-test.inboyu.com
        - dev-platform.inboyu.com
        - dev-exc.inboyu.com
        - dev-vm.inboyu.com
        - dev-am.inboyu.com
        - dev-md.inboyu.com
        - dev-qy.inboyu.com
        - dev-ac.inboyu.com
        - dev-scc.inboyu.com
        - dev-api.inboyu.com
        - data-encryption-service
    ports:
    - mode: ingress
      target: 80
      published: "80"
      protocol: tcp
    - mode: ingress
      target: 443
      published: "443"
      protocol: tcp
    restart: always
    volumes:
    - type: bind
      source: /Users/kilvn/Documents/web/wwwroot
      target: /var/www
      bind:
        create_host_path: true
    - type: bind
      source: /Users/kilvn/Documents/web/laradock/logs/nginx
      target: /var/log/nginx
      bind:
        create_host_path: true
    - type: bind
      source: /Users/kilvn/Documents/web/laradock/nginx/sites
      target: /etc/nginx/sites-available
      bind:
        create_host_path: true
    - type: bind
      source: /Users/kilvn/Documents/web/laradock/nginx/stream
      target: /etc/nginx/stream
      bind:
        create_host_path: true
    - type: bind
      source: /Users/kilvn/Documents/web/laradock/nginx/ssl
      target: /etc/nginx/ssl
      bind:
        create_host_path: true
  php-fpm:
    build:
      context: /Users/kilvn/Documents/web/laradock/php-fpm
      dockerfile: ./php-fpm/Dockerfile
      args:
        ADDITIONAL_LOCALES: en_US.UTF-8 es_ES.UTF-8 fr_FR.UTF-8
        BASE_IMAGE_TAG_PREFIX: latest
        CHANGE_SOURCE: "false"
        DOWNGRADE_OPENSSL_TLS_AND_SECLEVEL: "false"
        DOWNGRADE_OPENSSL_TLS_VERSION: "1.2"
        IMAGEMAGICK_VERSION: latest
        INSTALL_ADDITIONAL_LOCALES: "false"
        INSTALL_AEROSPIKE: "false"
        INSTALL_AMQP: "false"
        INSTALL_APCU: "false"
        INSTALL_AUDIOWAVEFORM: "false"
        INSTALL_BCMATH: "true"
        INSTALL_BLACKFIRE: "false"
        INSTALL_BZ2: "false"
        INSTALL_CACHETOOL: "false"
        INSTALL_CALENDAR: "false"
        INSTALL_CASSANDRA: "false"
        INSTALL_DNSUTILS: "true"
        INSTALL_DOCKER_CLIENT: "false"
        INSTALL_ENCHANT: "false"
        INSTALL_EVENT: "false"
        INSTALL_EXIF: "false"
        INSTALL_FAKETIME: "false"
        INSTALL_FFMPEG: "false"
        INSTALL_GEARMAN: "false"
        INSTALL_GETTEXT: "true"
        INSTALL_GHOSTSCRIPT: "false"
        INSTALL_GMP: "false"
        INSTALL_GNUPG: "false"
        INSTALL_IMAGE_OPTIMIZERS: "true"
        INSTALL_IMAGEMAGICK: "true"
        INSTALL_IMAP: "false"
        INSTALL_INTL: "true"
        INSTALL_IONCUBE: "false"
        INSTALL_LDAP: "false"
        INSTALL_MAILPARSE: "false"
        INSTALL_MEMCACHED: "false"
        INSTALL_MONGO: "false"
        INSTALL_MSSQL: "false"
        INSTALL_MYSQL_CLIENT: "true"
        INSTALL_MYSQLI: "true"
        INSTALL_OCI8: "false"
        INSTALL_OPCACHE: "false"
        INSTALL_PCNTL: "false"
        INSTALL_PCOV: "false"
        INSTALL_PG_CLIENT: "false"
        INSTALL_PGSQL: "false"
        INSTALL_PHALCON: "false"
        INSTALL_PHPDBG: "false"
        INSTALL_PHPDECIMAL: "false"
        INSTALL_PHPREDIS: "true"
        INSTALL_PING: "false"
        INSTALL_POSTGIS: "false"
        INSTALL_RDKAFKA: "false"
        INSTALL_SMB: "false"
        INSTALL_SOAP: "true"
        INSTALL_SSDB: "false"
        INSTALL_SSH2: "false"
        INSTALL_SSHPASS: "false"
        INSTALL_SWOOLE: "false"
        INSTALL_TAINT: "false"
        INSTALL_TRADER: "false"
        INSTALL_WKHTMLTOPDF: "false"
        INSTALL_XDEBUG: "true"
        INSTALL_XHPROF: "false"
        INSTALL_XLSWRITER: "false"
        INSTALL_XMLRPC: "true"
        INSTALL_XSL: "false"
        INSTALL_YAML: "false"
        INSTALL_ZMQ: "false"
        INSTALL_ZOOKEEPER: "false"
        LARADOCK_PHALCON_VERSION: 5.0.0
        LARADOCK_PHP_VERSION: "8.2"
        LOCALE: POSIX
        PGID: "1000"
        PHP_FPM_NEW_RELIC: "false"
        PHP_FPM_NEW_RELIC_APP_NAME: app_name
        PHP_FPM_NEW_RELIC_KEY: "0000"
        PUID: "1000"
        WKHTMLTOPDF_VERSION: 0.12.6-1
        XDEBUG_PORT: "9003"
        http_proxy: null
        https_proxy: null
        no_proxy: null
    depends_on:
      workspace:
        condition: service_started
    environment:
      DOCKER_CERT_PATH: /certs/client
      DOCKER_HOST: tcp://docker-in-docker:2376
      DOCKER_TLS_CERTDIR: /certs
      DOCKER_TLS_VERIFY: "1"
      FAKETIME: "-0"
      PHP_IDE_CONFIG: serverName=laradock
      TZ: PRC
    expose:
    - "9000"
    extra_hosts:
    - dockerhost:10.0.75.1
    image: laradock/php-fpm:latest-8.2
    links:
    - docker-in-docker
    networks:
      backend: null
    ports:
    - mode: ingress
      target: 9003
      published: "9003"
      protocol: tcp
    restart: always
    volumes:
    - type: bind
      source: /Users/kilvn/Documents/web/laradock/php-fpm/php8.2.ini
      target: /usr/local/etc/php/php.ini
      bind:
        create_host_path: true
    - type: bind
      source: /Users/kilvn/Documents/web/wwwroot
      target: /var/www
      bind:
        create_host_path: true
    - type: volume
      source: docker-in-docker
      target: /certs/client
      volume: {}
    - type: bind
      source: /Users/kilvn/Documents/web/laradock/php-fpm/www.conf
      target: /usr/local/etc/php-fpm.d/www.conf
      bind:
        create_host_path: true
  redis:
    build:
      context: /Users/kilvn/Documents/web/laradock/redis
      dockerfile: ./redis/Dockerfile
    image: redis:latest
    networks:
      backend: null
    ports:
    - mode: ingress
      target: 6379
      published: "6379"
      protocol: tcp
    restart: always
    volumes:
    - type: bind
      source: /Users/kilvn/.laradock/data/redis
      target: /data
      bind:
        create_host_path: true
  workspace:
    build:
      context: /Users/kilvn/Documents/web/laradock/workspace
      dockerfile: ./workspace/Dockerfile
      args:
        AST_VERSION: 1.0.10
        BASE_IMAGE_TAG_PREFIX: latest
        BLACKFIRE_CLIENT_ID: <client_id>
        BLACKFIRE_CLIENT_TOKEN: <client_token>
        CHANGE_SOURCE: "false"
        CHROME_DRIVER_VERSION: "2.42"
        COMPOSER_AUTH_JSON: "false"
        COMPOSER_GLOBAL_INSTALL: "true"
        COMPOSER_REPO_PACKAGIST: ""
        COMPOSER_VERSION: "2"
        DRUSH_VERSION: 8.4.6
        IMAGEMAGICK_VERSION: latest
        INSTALL_AEROSPIKE: "false"
        INSTALL_AMQP: "false"
        INSTALL_AST: "true"
        INSTALL_AUDIOWAVEFORM: "false"
        INSTALL_BLACKFIRE: "false"
        INSTALL_BZ2: "false"
        INSTALL_CASSANDRA: "false"
        INSTALL_DEPLOYER: "false"
        INSTALL_DNSUTILS: "true"
        INSTALL_DOCKER_CLIENT: "false"
        INSTALL_DRUPAL_CONSOLE: "false"
        INSTALL_DRUSH: "false"
        INSTALL_DUSK_DEPS: "false"
        INSTALL_EVENT: "false"
        INSTALL_FFMPEG: "false"
        INSTALL_FSWATCH: "false"
        INSTALL_GEARMAN: "false"
        INSTALL_GIT_PROMPT: "true"
        INSTALL_GMP: "false"
        INSTALL_GNU_PARALLEL: "false"
        INSTALL_GNUPG: "false"
        INSTALL_GRAPHVIZ: "false"
        INSTALL_IMAGE_OPTIMIZERS: "false"
        INSTALL_IMAGEMAGICK: "false"
        INSTALL_IMAP: "false"
        INSTALL_INOTIFY: "false"
        INSTALL_IONCUBE: "false"
        INSTALL_LARAVEL_ENVOY: "false"
        INSTALL_LARAVEL_INSTALLER: "false"
        INSTALL_LDAP: "false"
        INSTALL_LIBPNG: "false"
        INSTALL_LINUXBREW: "false"
        INSTALL_LNAV: "false"
        INSTALL_MAILPARSE: "false"
        INSTALL_MC: "false"
        INSTALL_MEMCACHED: "true"
        INSTALL_MONGO: "false"
        INSTALL_MSSQL: "false"
        INSTALL_MYSQL_CLIENT: "false"
        INSTALL_NODE: "false"
        INSTALL_NPM_ANGULAR_CLI: "false"
        INSTALL_NPM_BOWER: "false"
        INSTALL_NPM_GULP: "false"
        INSTALL_NPM_VUE_CLI: "false"
        INSTALL_OCI8: "false"
        INSTALL_PCOV: "false"
        INSTALL_PG_CLIENT: "false"
        INSTALL_PHALCON: "false"
        INSTALL_PHPDBG: "false"
        INSTALL_PHPDECIMAL: "false"
        INSTALL_PHPREDIS: "true"
        INSTALL_PING: "false"
        INSTALL_PNPM: "false"
        INSTALL_POWERLINE: "false"
        INSTALL_PRESTISSIMO: "false"
        INSTALL_PROTOC: "false"
        INSTALL_PYTHON: "false"
        INSTALL_PYTHON3: "true"
        INSTALL_RDKAFKA: "false"
        INSTALL_SMB: "false"
        INSTALL_SOAP: "false"
        INSTALL_SSDB: "false"
        INSTALL_SSH2: "false"
        INSTALL_SSHPASS: "false"
        INSTALL_SUBVERSION: "false"
        INSTALL_SUPERVISOR: "true"
        INSTALL_SWOOLE: "false"
        INSTALL_SYMFONY: "false"
        INSTALL_TAINT: "false"
        INSTALL_TERRAFORM: "false"
        INSTALL_TRADER: "false"
        INSTALL_V8JS: "false"
        INSTALL_WKHTMLTOPDF: "false"
        INSTALL_WORKSPACE_SSH: "false"
        INSTALL_WP_CLI: "false"
        INSTALL_XDEBUG: "true"
        INSTALL_XLSWRITER: "false"
        INSTALL_XMLRPC: "false"
        INSTALL_XSL: "false"
        INSTALL_YAML: "false"
        INSTALL_YARN: "false"
        INSTALL_ZMQ: "false"
        INSTALL_ZOOKEEPER: "false"
        LARADOCK_PHALCON_VERSION: 5.0.0
        LARADOCK_PHP_VERSION: "8.2"
        NODE_VERSION: node
        NPM_FETCH_RETRIES: "2"
        NPM_FETCH_RETRY_FACTOR: "10"
        NPM_FETCH_RETRY_MAXTIMEOUT: "60000"
        NPM_FETCH_RETRY_MINTIMEOUT: "10000"
        NPM_REGISTRY: ""
        NVM_NODEJS_ORG_MIRROR: ""
        PGID: "1000"
        PROTOC_VERSION: latest
        PUID: "1000"
        SHELL_OH_MY_ZSH: "true"
        SHELL_OH_MY_ZSH_ALIASES: "true"
        SHELL_OH_MY_ZSH_AUTOSUGESTIONS: "true"
        TZ: PRC
        WKHTMLTOPDF_VERSION: 0.12.6-1
        XDEBUG_PORT: "9003"
        YARN_VERSION: latest
        http_proxy: null
        https_proxy: null
        no_proxy: null
    environment:
      CHOKIDAR_USEPOLLING: "true"
      DOCKER_CERT_PATH: /certs/client
      DOCKER_HOST: tcp://docker-in-docker:2376
      DOCKER_TLS_CERTDIR: /certs
      DOCKER_TLS_VERIFY: "1"
      PHP_IDE_CONFIG: serverName=laradock
    extra_hosts:
    - dockerhost:10.0.75.1
    image: laradock/workspace:latest-8.2
    links:
    - docker-in-docker
    networks:
      backend: null
      frontend: null
    ports:
    - mode: ingress
      target: 22
      published: "2222"
      protocol: tcp
    - mode: ingress
      target: 3000
      published: "3000"
      protocol: tcp
    - mode: ingress
      target: 3001
      published: "3001"
      protocol: tcp
    - mode: ingress
      target: 8080
      published: "8080"
      protocol: tcp
    - mode: ingress
      target: 8000
      published: "8001"
      protocol: tcp
    - mode: ingress
      target: 4200
      published: "4200"
      protocol: tcp
    - mode: ingress
      target: 5173
      published: "5173"
      protocol: tcp
    restart: always
    tty: true
    volumes:
    - type: bind
      source: /Users/kilvn/Documents/web/wwwroot
      target: /var/www
      bind:
        create_host_path: true
    - type: volume
      source: docker-in-docker
      target: /certs/client
      volume: {}
    - type: bind
      source: /Users/kilvn/Documents/web/laradock/php-worker/supervisord.d
      target: /etc/supervisord.d
      bind:
        create_host_path: true
networks:
  backend:
    name: laradock_backend
    driver: bridge
  frontend:
    name: laradock_frontend
    driver: bridge
volumes:
  docker-in-docker:
    name: laradock_docker-in-docker
    driver: local
