server:
    http_listen_port: 9080
    grpc_listen_port: 0

positions:
    filename: /var/lib/promtail/positions.yaml   # 游标记录上一次同步位置
    sync_period: 10s #10秒钟同步一次
    ignore_invalid_yaml: true

clients:
    - url: http://172.28.0.4:3100/loki/api/v1/push

scrape_configs:
- job_name: test-fth-log
  static_configs:
  - targets:
      - localhost
    labels:
      job: fth
      __path__: /var/lib/promtail/logs/*.log
